### ISSUE TITLE
关于DoH本身域名的解析似乎有问题

### ISSUE THREAD

**Issue by NagaseKouichi** [shawn1m/overture#257]
发现如果备用DNS只使用了一个DoH服务器，而主机53端口没有其他DNS服务来解析DNS，会导致overture无法得到国外域名的解析结果。

例如overture监听在5353，备用DNS使用opendns的DoH服务，而主机的53端口（dnsmasq）设置为转发到5353端口，没有其他DNS服务，会导致通过overture的5353端口解析国外域名无法查询到结果。是不是因为DoH的查询地址所用的域名（比如doh.opendns.com）无法解析的原因呢？

如果把主机的53端口转发到其他的DNS服务，这时通过overture的5353端口就可以获取到国外域名的查询结果。

https-dns-proxy这个软件会设置一个bootstrap dns，用于设置DoH的地址所用的域名的IP（例如doh.opendns.com的bootstrap dns就是208.67.222.222和208.67.220.220），不知道大佬是否可以参考？

**Comment by Mitsuhaxy** [comment]
> 发现如果备用DNS只使用了一个DoH服务器，而主机53端口没有其他DNS服务来解析DNS，会导致overture无法得到国外域名的解析结果。
> 
> 例如overture监听在5353，备用DNS使用opendns的DoH服务，而主机的53端口（dnsmasq）设置为转发到5353端口，没有其他DNS服务，会导致通过overture的5353端口解析国外域名无法查询到结果。是不是因为DoH的查询地址所用的域名（比如doh.opendns.com）无法解析的原因呢？
> 
> 如果把主机的53端口转发到其他的DNS服务，这时通过overture的5353端口就可以获取到国外域名的查询结果。
> 
> https-dns-proxy这个软件会设置一个bootstrap dns，用于设置DoH的地址所用的域名的IP（例如doh.opendns.com的bootstrap dns就是208.67.222.222和208.67.220.220），不知道大佬是否可以参考？

参考readme，可以将上游服务器修改格式为dns.xx.xx:853@x.x.x.x，例如：
```
alternativeDNS:
  - name: GoogleDNS
    address: dns.google:853@8.8.8.8
    protocol: tcp-tls
    socks5Address:
    timeout: 5
    ednsClientSubnet:
policy: disable
externalIP:
noCookie: true
```
