### ISSUE TITLE
Query a domain that no AAAA record will always fail

### ISSUE THREAD

**Issue by cielpy** [shawn1m/overture#259]
with [dog](https://dns.lookup.dog/) command manually

```
~ took 4s
❯ dog -T @8.8.8.8 AAAA github.com
SOA github.com. 21m51s A "dns1.p08.nsone.net." "hostmaster.nsone.net." 1618573167 12h00m00s 2h00m00s 14d0h00m00s 1h00m00s

~
❯ dog -T @8.8.8.8 AAAA z-lib.org
SOA z-lib.org. 29m19s A "ns1.z-lib.org." "hostmaster.z-lib.org." 1619742165 3h00m00s 1h00m00s 7d0h00m00s 1h00m00s
```

with overture, always fail.

```
❯ dog AAAA z-lib.org
Status: Server Failure
```

query some domain that has AAAA record is fine

```
~ took 4s
❯ dog wq.io AAAA
AAAA wq.io. 5m00s   2604:a880:1:20::5b:5001

```

here is my config

```yaml
bindAddress: :7053
debugHTTPAddress: 127.0.0.1:5555
dohEnabled: false
primaryDNS:
  - name: DNSPod
    address: 119.29.29.29:53
    protocol: udp
    socks5Address:
    timeout: 6
    ednsClientSubnet:
      policy: disable
      externalIP:
      noCookie: true
  - name: Ali
    address: 223.5.5.5:53
    protocol: udp
    socks5Address:
    timeout: 6
    ednsClientSubnet:
      policy: disable
      externalIP:
      noCookie: true
  - name: 114
    address: 114.114.114.114:53
    protocol: udp
    socks5Address:
    timeout: 6
    ednsClientSubnet:
      policy: disable
      externalIP:
      noCookie: true
alternativeDNS:
  - name: NextTLS
    address: xxx.dns.nextdns.io:853@45.90.28.89
    protocol: tcp-tls
    socks5Address: "127.0.0.1:7891"
    timeout: 3
    ednsClientSubnet:
      policy: disable
      externalIP:
      noCookie: true
  - name: GoogleTLS
    address: dns.google:853@8.8.8.8
    protocol: tcp-tls
    socks5Address:
    timeout: 6
    ednsClientSubnet:
      policy: disable
      externalIP:
      noCookie: true
  - name: Google
    address: 8.8.8.8:53
    protocol: tcp
    socks5Address:
    timeout: 6
    ednsClientSubnet:
      policy: disable
      externalIP:
      noCookie: true
onlyPrimaryDNS: false
ipv6UseAlternativeDNS: false
alternativeDNSConcurrent: false
whenPrimaryDNSAnswerNoneUse: primaryDNS
ipNetworkFile:
  primary: /etc/overture/ip_network_primary
  alternative: /etc/overture/ip_network_alternative
domainFile:
  primary: /etc/overture/domain_primary
  alternative:  /etc/overture/domain_alternative
  matcher: suffix-tree
hostsFile:
  hostsFile: /etc/overture/hosts
  finder: full-map
minimumTTL: 0
domainTTLFile: /etc/overture//domain_ttl
cacheSize: 10000
rejectQType:
  - 255
```

log

```
time="2021-05-01 04:29:09" level=debug msg="Question from 127.0.0.1: ;z-lib.org.\tIN\t AAAA"
time="2021-05-01 04:29:09" level=debug msg=Matched DNS=Alternative domain=z-lib.org question=z-lib.org
time="2021-05-01 04:29:11" level=debug msg="Question from 127.0.0.1: ;z-lib.org.\tIN\t AAAA"
time="2021-05-01 04:29:11" level=debug msg=Matched DNS=Alternative domain=z-lib.org question=z-lib.org
```
