### ISSUE TITLE
A connection attempt failed because the connected party did not properly respond after a period of time

### ISSUE THREAD

**Issue by salzburgrujvnun** [shawn1m/overture#265]
具体如何配置文件？

报错信息
```log
 A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

```yaml
primaryDNS:
  - name: GoogleDoH
    address: https://dns.google/dns-query
    protocol: https
    socks5Address: 172.0.0.1:7890
    timeout: 6
    ednsClientSubnet:
      policy: disable
      externalIP:
      noCookie: true
```

服务节点，使用 vmess， trojan。

![image](https://user-images.githubusercontent.com/79001470/130327886-23dc438e-845b-466f-9da6-085c95340dff.png)
