### ISSUE TITLE
即使有缓存，解析速度有时也慢的问题

### ISSUE THREAD

**Issue by Franinc** [shawn1m/overture#282]
设置了三个dns，因为最近会随机被ban其中一两个dns 所以第一次解析速度慢很正常，但我发现即使debug页显示某域名已有缓存 也没过期的情况下，第二次第三次第四次再解析同一个域名，即使每次间隔时间都很短 也经常出现等几秒才会返回解析结果（小部分会立即返回结果）。
dns架设在本地 版本v1.8 win10
```
bindAddress: 127.0.0.2:53
debugHTTPAddress: 127.0.0.1:5555
dohEnabled: false
primaryDNS:
  - name: opendns
    address: 208.67.222.222:5353
    protocol: udp
    socks5Address:
    timeout: 6
    ednsClientSubnet:
      policy: auto
      externalIP: 码
      noCookie: true
alternativeDNS:
  - name: cloudflare
    address: https://1.1.1.1/dns-query
    protocol: https
    socks5Address:
    timeout: 6
    ednsClientSubnet:
      policy: auto
      externalIP: 码
      noCookie: true
  - name: opendns2
    address: 208.67.220.220:5353
    protocol: udp
    socks5Address:
    timeout: 6
    ednsClientSubnet:
      policy: auto
      externalIP: 码
      noCookie: true
onlyPrimaryDNS: false
ipv6UseAlternativeDNS: false
alternativeDNSConcurrent: true
whenPrimaryDNSAnswerNoneUse: alternativeDNS
ipNetworkFile:
  primary: ./ip_network_primary_sample
  alternative: ./ip_network_alternative_sample
domainFile:
  primary: ./domain_primary_sample
  alternative: ./domain_alternative_sample
  matcher: full-map
hostsFile:
  hostsFile: ./hosts_sample
  finder: regex-list
minimumTTL: 300
domainTTLFile: ./domain_ttl_sample
cacheSize: 2048
cacheRedisUrl:
cacheRedisConnectionPoolSize:
rejectQType:
  - 255
```
