### ISSUE TITLE
当我使用mix-list分流时，部分域名不能选择正确的上游服务器

### ISSUE THREAD

**Issue by zyOverture** [shawn1m/overture#291]
我直接使用Loyalsoldier项目的direct-list.txt作为domain_primary，使用proxy-list.txt作为domain_alternative，matcher选择mix-list
然而调用overture来获取www.apple.com的域名时，无法匹配上domain_primary，实际上，domain_primary中包含有full:www.apple.com
<img width="945" alt="image" src="https://github.com/shawn1m/overture/assets/39595404/5d8fcb53-e702-4c3c-b7d1-4a2bb6b467d4">

domain_primary:
https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/direct-list.txt
domain_alternative:
https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/proxy-list.txt
ip_network_primary:
https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/cn.txt
hosts/domain_ttl/ip_network_alternative等均为默认

我的配置文件如下
```
bindAddress: :853
debugHTTPAddress: 127.0.0.1:5555
dohEnabled: false
primaryDNS:
  - name: AliDOH
    address: https://dns.alidns.com@223.5.5.5/dns-query
    protocol: https
    socks5Address:
    timeout: 60
    ednsClientSubnet:
      policy: manual
      externalIP: x.x.x.x
      noCookie: true
alternativeDNS:
  - name: GOOGLE
    address: https://dns.google@8.8.8.8/dns-query
    protocol: https
    socks5Address: 127.0.0.1:1080
    timeout: 60
    ednsClientSubnet:
      policy: disable
      externalIP:
      noCookie: true
  - name: ONE
    address: https://one.one.one.one@1.1.1.1/dns-query
    protocol: https
    socks5Address: 127.0.0.1:1080
    timeout: 60
    ednsClientSubnet:
      policy: disable
      externalIP:
      noCookie: true
onlyPrimaryDNS: false
ipv6UseAlternativeDNS: false
alternativeDNSConcurrent: false
whenPrimaryDNSAnswerNoneUse: primaryDNS
ipNetworkFile:
  primary: /opt/overture/ip_network_primary
  alternative: /opt/overture/ip_network_alternative
domainFile:
  primary: /opt/overture/domain_primary
  alternative: /opt/overture/domain_alternative
  matcher: mix-list
hostsFile:
  hostsFile: /opt/overture/hosts
  finder: full-map
minimumTTL: 172800
domainTTLFile: /opt/overture/domain_ttl
cacheSize: 40960
cacheRedisUrl: redis://127.0.0.1:6379/0
cacheRedisConnectionPoolSize: 20
rejectQType:
  - 255
```
